FROM tomcat:8.0

MAINTAINER "Oscar Alejandro Gomez <oscaragr1990@gmail.com>"

ADD settings.xml /usr/local/tomcat/conf/
ADD tomcat-users.xml /usr/local/tomcat/conf/
ADD appFibonacci.war /usr/local/tomcat/webapps/

